ALTER TABLE public.team ALTER COLUMN number_of_matches DROP NOT NULL;
ALTER TABLE public.team ALTER COLUMN wins DROP NOT NULL;
ALTER TABLE public.team ALTER COLUMN draws DROP NOT NULL;
ALTER TABLE public.team ALTER COLUMN loses DROP NOT NULL;
ALTER TABLE public.team ALTER COLUMN goals_for DROP NOT NULL;
ALTER TABLE public.team ALTER COLUMN goals_against DROP NOT NULL;
ALTER TABLE public.team ALTER COLUMN balance DROP NOT NULL;
ALTER TABLE public.team ALTER COLUMN points DROP NOT NULL;
